name: test

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ironcore864/gitops-argocd
      - name: Commit files
        run: |
          sed -i "s/^appVersion: .*$/appVersion: "2"/" go-hello-http/Chart.yaml
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.MY_GH_TOKEN }}
          repository: ironcore864/gitops-argocd
